---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	greet(greet)
	wait_auth(wait_auth)
	auth_interpret(auth_interpret)
	auth_check(auth_check)
	offer_human(offer_human)
	post_auth(post_auth)
	wait_main(wait_main)
	classify(classify)
	small_talk(small_talk)
	dispatch(dispatch)
	after_request(after_request)
	anything_else(anything_else)
	goodbye(goodbye)
	__end__([<p>__end__</p>]):::last
	__start__ --> greet;
	after_request -. &nbsp;end&nbsp; .-> __end__;
	after_request -.-> dispatch;
	anything_else --> wait_main;
	auth_check -.-> offer_human;
	auth_check -.-> post_auth;
	auth_check -.-> wait_auth;
	auth_interpret -.-> auth_check;
	auth_interpret -.-> dispatch;
	auth_interpret -.-> goodbye;
	auth_interpret -.-> wait_auth;
	cancel_order\3afinish --> after_request;
	classify -.-> dispatch;
	classify -.-> goodbye;
	classify -.-> small_talk;
	classify -.-> wait_main;
	dispatch -.-> anything_else;
	dispatch -.-> cancel_order\3astart;
	dispatch -.-> exchange_items\3astart;
	dispatch -.-> goodbye;
	dispatch -.-> info\3aanswer;
	dispatch -.-> modify_default_address\3astart;
	dispatch -.-> modify_order_address\3astart;
	dispatch -.-> modify_order_items\3astart;
	dispatch -.-> modify_order_payment\3astart;
	dispatch -.-> return_items\3astart;
	dispatch -.-> transfer\3atransfer;
	exchange_items\3afinish --> after_request;
	greet --> wait_auth;
	info\3aanswer --> after_request;
	modify_default_address\3afinish --> after_request;
	modify_order_address\3afinish --> after_request;
	modify_order_items\3afinish --> after_request;
	modify_order_payment\3afinish --> after_request;
	offer_human -.-> dispatch;
	offer_human -.-> wait_auth;
	post_auth -.-> classify;
	post_auth -.-> wait_main;
	return_items\3afinish --> after_request;
	small_talk --> wait_main;
	transfer\3atransfer --> after_request;
	wait_auth --> auth_interpret;
	wait_main --> classify;
	goodbye --> __end__;
	subgraph cancel_order
	cancel_order\3astart(start)
	cancel_order\3ainterpret(interpret)
	cancel_order\3afind_order(find_order)
	cancel_order\3acheck_pending(check_pending)
	cancel_order\3acheck_reason(check_reason)
	cancel_order\3aprepare_summary(prepare_summary)
	cancel_order\3aask(ask)
	cancel_order\3await(wait)
	cancel_order\3adeny(deny)
	cancel_order\3aconfirm(confirm)
	cancel_order\3aafter_confirm(after_confirm)
	cancel_order\3aexecute(execute)
	cancel_order\3adropped(dropped)
	cancel_order\3afinish(finish)
	cancel_order\3aafter_confirm -.-> cancel_order\3aexecute;
	cancel_order\3aafter_confirm -.-> cancel_order\3afinish;
	cancel_order\3aafter_confirm -.-> cancel_order\3await;
	cancel_order\3aask -.-> cancel_order\3await;
	cancel_order\3acheck_pending -.-> cancel_order\3aask;
	cancel_order\3acheck_pending -.-> cancel_order\3acheck_reason;
	cancel_order\3acheck_pending -.-> cancel_order\3adeny;
	cancel_order\3acheck_pending -.-> cancel_order\3adropped;
	cancel_order\3acheck_reason -.-> cancel_order\3aask;
	cancel_order\3acheck_reason -.-> cancel_order\3adeny;
	cancel_order\3acheck_reason -.-> cancel_order\3adropped;
	cancel_order\3acheck_reason -.-> cancel_order\3aprepare_summary;
	cancel_order\3aconfirm -.-> cancel_order\3aafter_confirm;
	cancel_order\3adeny -.-> cancel_order\3afinish;
	cancel_order\3adropped -.-> cancel_order\3afinish;
	cancel_order\3aexecute -.-> cancel_order\3afinish;
	cancel_order\3afind_order -.-> cancel_order\3aask;
	cancel_order\3afind_order -.-> cancel_order\3acheck_pending;
	cancel_order\3afind_order -.-> cancel_order\3adeny;
	cancel_order\3afind_order -.-> cancel_order\3adropped;
	cancel_order\3ainterpret -.-> cancel_order\3adropped;
	cancel_order\3ainterpret -.-> cancel_order\3afind_order;
	cancel_order\3ainterpret -.-> cancel_order\3await;
	cancel_order\3aprepare_summary -.-> cancel_order\3aconfirm;
	cancel_order\3astart -.-> cancel_order\3ainterpret;
	cancel_order\3await --> cancel_order\3ainterpret;
	end
	subgraph modify_order_address
	modify_order_address\3astart(start)
	modify_order_address\3ainterpret(interpret)
	modify_order_address\3afind_order(find_order)
	modify_order_address\3acheck_pending(check_pending)
	modify_order_address\3acheck_new_address(check_new_address)
	modify_order_address\3aprepare_summary(prepare_summary)
	modify_order_address\3aask(ask)
	modify_order_address\3await(wait)
	modify_order_address\3adeny(deny)
	modify_order_address\3aconfirm(confirm)
	modify_order_address\3aafter_confirm(after_confirm)
	modify_order_address\3aexecute(execute)
	modify_order_address\3adropped(dropped)
	modify_order_address\3afinish(finish)
	modify_order_address\3aafter_confirm -.-> modify_order_address\3aexecute;
	modify_order_address\3aafter_confirm -.-> modify_order_address\3afinish;
	modify_order_address\3aafter_confirm -.-> modify_order_address\3await;
	modify_order_address\3aask -.-> modify_order_address\3await;
	modify_order_address\3acheck_new_address -.-> modify_order_address\3aask;
	modify_order_address\3acheck_new_address -.-> modify_order_address\3adeny;
	modify_order_address\3acheck_new_address -.-> modify_order_address\3adropped;
	modify_order_address\3acheck_new_address -.-> modify_order_address\3aprepare_summary;
	modify_order_address\3acheck_pending -.-> modify_order_address\3aask;
	modify_order_address\3acheck_pending -.-> modify_order_address\3acheck_new_address;
	modify_order_address\3acheck_pending -.-> modify_order_address\3adeny;
	modify_order_address\3acheck_pending -.-> modify_order_address\3adropped;
	modify_order_address\3aconfirm -.-> modify_order_address\3aafter_confirm;
	modify_order_address\3adeny -.-> modify_order_address\3afinish;
	modify_order_address\3adropped -.-> modify_order_address\3afinish;
	modify_order_address\3aexecute -.-> modify_order_address\3afinish;
	modify_order_address\3afind_order -.-> modify_order_address\3aask;
	modify_order_address\3afind_order -.-> modify_order_address\3acheck_pending;
	modify_order_address\3afind_order -.-> modify_order_address\3adeny;
	modify_order_address\3afind_order -.-> modify_order_address\3adropped;
	modify_order_address\3ainterpret -.-> modify_order_address\3adropped;
	modify_order_address\3ainterpret -.-> modify_order_address\3afind_order;
	modify_order_address\3ainterpret -.-> modify_order_address\3await;
	modify_order_address\3aprepare_summary -.-> modify_order_address\3aconfirm;
	modify_order_address\3astart -.-> modify_order_address\3ainterpret;
	modify_order_address\3await --> modify_order_address\3ainterpret;
	end
	subgraph modify_order_payment
	modify_order_payment\3astart(start)
	modify_order_payment\3ainterpret(interpret)
	modify_order_payment\3afind_order(find_order)
	modify_order_payment\3acheck_pending(check_pending)
	modify_order_payment\3acheck_single_payment(check_single_payment)
	modify_order_payment\3achoose_payment_method(choose_payment_method)
	modify_order_payment\3acheck_gift_card_balance(check_gift_card_balance)
	modify_order_payment\3aprepare_summary(prepare_summary)
	modify_order_payment\3aask(ask)
	modify_order_payment\3await(wait)
	modify_order_payment\3adeny(deny)
	modify_order_payment\3aconfirm(confirm)
	modify_order_payment\3aafter_confirm(after_confirm)
	modify_order_payment\3aexecute(execute)
	modify_order_payment\3adropped(dropped)
	modify_order_payment\3afinish(finish)
	modify_order_payment\3aafter_confirm -.-> modify_order_payment\3aexecute;
	modify_order_payment\3aafter_confirm -.-> modify_order_payment\3afinish;
	modify_order_payment\3aafter_confirm -.-> modify_order_payment\3await;
	modify_order_payment\3aask -.-> modify_order_payment\3await;
	modify_order_payment\3acheck_gift_card_balance -.-> modify_order_payment\3aask;
	modify_order_payment\3acheck_gift_card_balance -.-> modify_order_payment\3adeny;
	modify_order_payment\3acheck_gift_card_balance -.-> modify_order_payment\3adropped;
	modify_order_payment\3acheck_gift_card_balance -.-> modify_order_payment\3aprepare_summary;
	modify_order_payment\3acheck_pending -.-> modify_order_payment\3aask;
	modify_order_payment\3acheck_pending -.-> modify_order_payment\3acheck_single_payment;
	modify_order_payment\3acheck_pending -.-> modify_order_payment\3adeny;
	modify_order_payment\3acheck_pending -.-> modify_order_payment\3adropped;
	modify_order_payment\3acheck_single_payment -.-> modify_order_payment\3aask;
	modify_order_payment\3acheck_single_payment -.-> modify_order_payment\3achoose_payment_method;
	modify_order_payment\3acheck_single_payment -.-> modify_order_payment\3adeny;
	modify_order_payment\3acheck_single_payment -.-> modify_order_payment\3adropped;
	modify_order_payment\3achoose_payment_method -.-> modify_order_payment\3aask;
	modify_order_payment\3achoose_payment_method -.-> modify_order_payment\3acheck_gift_card_balance;
	modify_order_payment\3achoose_payment_method -.-> modify_order_payment\3adeny;
	modify_order_payment\3achoose_payment_method -.-> modify_order_payment\3adropped;
	modify_order_payment\3aconfirm -.-> modify_order_payment\3aafter_confirm;
	modify_order_payment\3adeny -.-> modify_order_payment\3afinish;
	modify_order_payment\3adropped -.-> modify_order_payment\3afinish;
	modify_order_payment\3aexecute -.-> modify_order_payment\3afinish;
	modify_order_payment\3afind_order -.-> modify_order_payment\3aask;
	modify_order_payment\3afind_order -.-> modify_order_payment\3acheck_pending;
	modify_order_payment\3afind_order -.-> modify_order_payment\3adeny;
	modify_order_payment\3afind_order -.-> modify_order_payment\3adropped;
	modify_order_payment\3ainterpret -.-> modify_order_payment\3adropped;
	modify_order_payment\3ainterpret -.-> modify_order_payment\3afind_order;
	modify_order_payment\3ainterpret -.-> modify_order_payment\3await;
	modify_order_payment\3aprepare_summary -.-> modify_order_payment\3aconfirm;
	modify_order_payment\3astart -.-> modify_order_payment\3ainterpret;
	modify_order_payment\3await --> modify_order_payment\3ainterpret;
	end
	subgraph modify_order_items
	modify_order_items\3astart(start)
	modify_order_items\3ainterpret(interpret)
	modify_order_items\3afind_order(find_order)
	modify_order_items\3acheck_pending(check_pending)
	modify_order_items\3afind_items(find_items)
	modify_order_items\3achoose_new_options(choose_new_options)
	modify_order_items\3achoose_payment_method(choose_payment_method)
	modify_order_items\3acheck_gift_card_balance(check_gift_card_balance)
	modify_order_items\3aprepare_summary(prepare_summary)
	modify_order_items\3aask(ask)
	modify_order_items\3await(wait)
	modify_order_items\3adeny(deny)
	modify_order_items\3aconfirm(confirm)
	modify_order_items\3aafter_confirm(after_confirm)
	modify_order_items\3aexecute(execute)
	modify_order_items\3adropped(dropped)
	modify_order_items\3afinish(finish)
	modify_order_items\3aafter_confirm -.-> modify_order_items\3aexecute;
	modify_order_items\3aafter_confirm -.-> modify_order_items\3afinish;
	modify_order_items\3aafter_confirm -.-> modify_order_items\3await;
	modify_order_items\3aask -.-> modify_order_items\3await;
	modify_order_items\3acheck_gift_card_balance -.-> modify_order_items\3aask;
	modify_order_items\3acheck_gift_card_balance -.-> modify_order_items\3adeny;
	modify_order_items\3acheck_gift_card_balance -.-> modify_order_items\3adropped;
	modify_order_items\3acheck_gift_card_balance -.-> modify_order_items\3aprepare_summary;
	modify_order_items\3acheck_pending -.-> modify_order_items\3aask;
	modify_order_items\3acheck_pending -.-> modify_order_items\3adeny;
	modify_order_items\3acheck_pending -.-> modify_order_items\3adropped;
	modify_order_items\3acheck_pending -.-> modify_order_items\3afind_items;
	modify_order_items\3achoose_new_options -.-> modify_order_items\3aask;
	modify_order_items\3achoose_new_options -.-> modify_order_items\3achoose_payment_method;
	modify_order_items\3achoose_new_options -.-> modify_order_items\3adeny;
	modify_order_items\3achoose_new_options -.-> modify_order_items\3adropped;
	modify_order_items\3achoose_payment_method -.-> modify_order_items\3aask;
	modify_order_items\3achoose_payment_method -.-> modify_order_items\3acheck_gift_card_balance;
	modify_order_items\3achoose_payment_method -.-> modify_order_items\3adeny;
	modify_order_items\3achoose_payment_method -.-> modify_order_items\3adropped;
	modify_order_items\3aconfirm -.-> modify_order_items\3aafter_confirm;
	modify_order_items\3adeny -.-> modify_order_items\3afinish;
	modify_order_items\3adropped -.-> modify_order_items\3afinish;
	modify_order_items\3aexecute -.-> modify_order_items\3afinish;
	modify_order_items\3afind_items -.-> modify_order_items\3aask;
	modify_order_items\3afind_items -.-> modify_order_items\3achoose_new_options;
	modify_order_items\3afind_items -.-> modify_order_items\3adeny;
	modify_order_items\3afind_items -.-> modify_order_items\3adropped;
	modify_order_items\3afind_order -.-> modify_order_items\3aask;
	modify_order_items\3afind_order -.-> modify_order_items\3acheck_pending;
	modify_order_items\3afind_order -.-> modify_order_items\3adeny;
	modify_order_items\3afind_order -.-> modify_order_items\3adropped;
	modify_order_items\3ainterpret -.-> modify_order_items\3adropped;
	modify_order_items\3ainterpret -.-> modify_order_items\3afind_order;
	modify_order_items\3ainterpret -.-> modify_order_items\3await;
	modify_order_items\3aprepare_summary -.-> modify_order_items\3aconfirm;
	modify_order_items\3astart -.-> modify_order_items\3ainterpret;
	modify_order_items\3await --> modify_order_items\3ainterpret;
	end
	subgraph return_items
	return_items\3astart(start)
	return_items\3ainterpret(interpret)
	return_items\3afind_order(find_order)
	return_items\3acheck_delivered(check_delivered)
	return_items\3acheck_returns_not_blocked(check_returns_not_blocked)
	return_items\3afind_items(find_items)
	return_items\3achoose_refund_method(choose_refund_method)
	return_items\3aprepare_summary(prepare_summary)
	return_items\3aask(ask)
	return_items\3await(wait)
	return_items\3adeny(deny)
	return_items\3aconfirm(confirm)
	return_items\3aafter_confirm(after_confirm)
	return_items\3aexecute(execute)
	return_items\3adropped(dropped)
	return_items\3afinish(finish)
	return_items\3aapproval_gate(approval_gate)
	return_items\3aapproval(approval)
	return_items\3aafter_approval(after_approval)
	return_items\3aoffer_transfer(offer_transfer)
	return_items\3aafter_offer(after_offer)
	return_items\3aafter_approval -.-> return_items\3aexecute;
	return_items\3aafter_approval -.-> return_items\3aoffer_transfer;
	return_items\3aafter_confirm -.-> return_items\3aapproval_gate;
	return_items\3aafter_confirm -.-> return_items\3afinish;
	return_items\3aafter_confirm -.-> return_items\3await;
	return_items\3aafter_offer -.-> return_items\3afinish;
	return_items\3aapproval -.-> return_items\3aafter_approval;
	return_items\3aapproval_gate -.-> return_items\3aapproval;
	return_items\3aapproval_gate -.-> return_items\3aexecute;
	return_items\3aask -.-> return_items\3await;
	return_items\3acheck_delivered -.-> return_items\3aask;
	return_items\3acheck_delivered -.-> return_items\3acheck_returns_not_blocked;
	return_items\3acheck_delivered -.-> return_items\3adeny;
	return_items\3acheck_delivered -.-> return_items\3adropped;
	return_items\3acheck_returns_not_blocked -.-> return_items\3aask;
	return_items\3acheck_returns_not_blocked -.-> return_items\3adeny;
	return_items\3acheck_returns_not_blocked -.-> return_items\3adropped;
	return_items\3acheck_returns_not_blocked -.-> return_items\3afind_items;
	return_items\3achoose_refund_method -.-> return_items\3aask;
	return_items\3achoose_refund_method -.-> return_items\3adeny;
	return_items\3achoose_refund_method -.-> return_items\3adropped;
	return_items\3achoose_refund_method -.-> return_items\3aprepare_summary;
	return_items\3aconfirm -.-> return_items\3aafter_confirm;
	return_items\3adeny -.-> return_items\3afinish;
	return_items\3adropped -.-> return_items\3afinish;
	return_items\3aexecute -.-> return_items\3afinish;
	return_items\3afind_items -.-> return_items\3aask;
	return_items\3afind_items -.-> return_items\3achoose_refund_method;
	return_items\3afind_items -.-> return_items\3adeny;
	return_items\3afind_items -.-> return_items\3adropped;
	return_items\3afind_order -.-> return_items\3aask;
	return_items\3afind_order -.-> return_items\3acheck_delivered;
	return_items\3afind_order -.-> return_items\3adeny;
	return_items\3afind_order -.-> return_items\3adropped;
	return_items\3ainterpret -.-> return_items\3adropped;
	return_items\3ainterpret -.-> return_items\3afind_order;
	return_items\3ainterpret -.-> return_items\3await;
	return_items\3aoffer_transfer -.-> return_items\3aafter_offer;
	return_items\3aprepare_summary -.-> return_items\3aconfirm;
	return_items\3astart -.-> return_items\3ainterpret;
	return_items\3await --> return_items\3ainterpret;
	end
	subgraph exchange_items
	exchange_items\3astart(start)
	exchange_items\3ainterpret(interpret)
	exchange_items\3afind_order(find_order)
	exchange_items\3acheck_delivered(check_delivered)
	exchange_items\3afind_items(find_items)
	exchange_items\3achoose_new_options(choose_new_options)
	exchange_items\3achoose_payment_method(choose_payment_method)
	exchange_items\3acheck_gift_card_balance(check_gift_card_balance)
	exchange_items\3aprepare_summary(prepare_summary)
	exchange_items\3aask(ask)
	exchange_items\3await(wait)
	exchange_items\3adeny(deny)
	exchange_items\3aconfirm(confirm)
	exchange_items\3aafter_confirm(after_confirm)
	exchange_items\3aexecute(execute)
	exchange_items\3adropped(dropped)
	exchange_items\3afinish(finish)
	exchange_items\3aafter_confirm -.-> exchange_items\3aexecute;
	exchange_items\3aafter_confirm -.-> exchange_items\3afinish;
	exchange_items\3aafter_confirm -.-> exchange_items\3await;
	exchange_items\3aask -.-> exchange_items\3await;
	exchange_items\3acheck_delivered -.-> exchange_items\3aask;
	exchange_items\3acheck_delivered -.-> exchange_items\3adeny;
	exchange_items\3acheck_delivered -.-> exchange_items\3adropped;
	exchange_items\3acheck_delivered -.-> exchange_items\3afind_items;
	exchange_items\3acheck_gift_card_balance -.-> exchange_items\3aask;
	exchange_items\3acheck_gift_card_balance -.-> exchange_items\3adeny;
	exchange_items\3acheck_gift_card_balance -.-> exchange_items\3adropped;
	exchange_items\3acheck_gift_card_balance -.-> exchange_items\3aprepare_summary;
	exchange_items\3achoose_new_options -.-> exchange_items\3aask;
	exchange_items\3achoose_new_options -.-> exchange_items\3achoose_payment_method;
	exchange_items\3achoose_new_options -.-> exchange_items\3adeny;
	exchange_items\3achoose_new_options -.-> exchange_items\3adropped;
	exchange_items\3achoose_payment_method -.-> exchange_items\3aask;
	exchange_items\3achoose_payment_method -.-> exchange_items\3acheck_gift_card_balance;
	exchange_items\3achoose_payment_method -.-> exchange_items\3adeny;
	exchange_items\3achoose_payment_method -.-> exchange_items\3adropped;
	exchange_items\3aconfirm -.-> exchange_items\3aafter_confirm;
	exchange_items\3adeny -.-> exchange_items\3afinish;
	exchange_items\3adropped -.-> exchange_items\3afinish;
	exchange_items\3aexecute -.-> exchange_items\3afinish;
	exchange_items\3afind_items -.-> exchange_items\3aask;
	exchange_items\3afind_items -.-> exchange_items\3achoose_new_options;
	exchange_items\3afind_items -.-> exchange_items\3adeny;
	exchange_items\3afind_items -.-> exchange_items\3adropped;
	exchange_items\3afind_order -.-> exchange_items\3aask;
	exchange_items\3afind_order -.-> exchange_items\3acheck_delivered;
	exchange_items\3afind_order -.-> exchange_items\3adeny;
	exchange_items\3afind_order -.-> exchange_items\3adropped;
	exchange_items\3ainterpret -.-> exchange_items\3adropped;
	exchange_items\3ainterpret -.-> exchange_items\3afind_order;
	exchange_items\3ainterpret -.-> exchange_items\3await;
	exchange_items\3aprepare_summary -.-> exchange_items\3aconfirm;
	exchange_items\3astart -.-> exchange_items\3ainterpret;
	exchange_items\3await --> exchange_items\3ainterpret;
	end
	subgraph modify_default_address
	modify_default_address\3astart(start)
	modify_default_address\3ainterpret(interpret)
	modify_default_address\3acheck_new_address(check_new_address)
	modify_default_address\3aprepare_summary(prepare_summary)
	modify_default_address\3aask(ask)
	modify_default_address\3await(wait)
	modify_default_address\3adeny(deny)
	modify_default_address\3aconfirm(confirm)
	modify_default_address\3aafter_confirm(after_confirm)
	modify_default_address\3aexecute(execute)
	modify_default_address\3adropped(dropped)
	modify_default_address\3afinish(finish)
	modify_default_address\3aafter_confirm -.-> modify_default_address\3aexecute;
	modify_default_address\3aafter_confirm -.-> modify_default_address\3afinish;
	modify_default_address\3aafter_confirm -.-> modify_default_address\3await;
	modify_default_address\3aask -.-> modify_default_address\3await;
	modify_default_address\3acheck_new_address -.-> modify_default_address\3aask;
	modify_default_address\3acheck_new_address -.-> modify_default_address\3adeny;
	modify_default_address\3acheck_new_address -.-> modify_default_address\3adropped;
	modify_default_address\3acheck_new_address -.-> modify_default_address\3aprepare_summary;
	modify_default_address\3aconfirm -.-> modify_default_address\3aafter_confirm;
	modify_default_address\3adeny -.-> modify_default_address\3afinish;
	modify_default_address\3adropped -.-> modify_default_address\3afinish;
	modify_default_address\3aexecute -.-> modify_default_address\3afinish;
	modify_default_address\3ainterpret -.-> modify_default_address\3acheck_new_address;
	modify_default_address\3ainterpret -.-> modify_default_address\3adropped;
	modify_default_address\3ainterpret -.-> modify_default_address\3await;
	modify_default_address\3aprepare_summary -.-> modify_default_address\3aconfirm;
	modify_default_address\3astart -.-> modify_default_address\3ainterpret;
	modify_default_address\3await --> modify_default_address\3ainterpret;
	end
	subgraph info
	info\3aanswer(answer)
	end
	subgraph transfer
	transfer\3atransfer(transfer)
	end
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
